######################################################################
# Automatically generated by qmake (2.01a) Fri May 28 12:25:15 2010
######################################################################

TEMPLATE = app
TARGET = snails
DEPENDPATH += .
INCLUDEPATH += /usr/include/qt4/QtGui/ /usr/include/fapws
LIBS += -lfapws

QMAKE_CXXFLAGS += -D_PLAT_LINUX_

# Input

HEADERS += snails.h

SOURCES += snails.cpp
